# ################################
# Model: wav2vec2 + DNN + CTC
# Augmentation: SpecAugment
# Taken from Librispeech recipe
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 2000
# lr: 1.0e-4
lr: 0.9
lr_wav2vec: 0.0000008
number_of_epochs: 100
# w2v_model: wav2vec2-large-xlsr-53
# w2v_model: wav2vec2-large-960h-lv60-self
w2v_model: hubert-large-ls960-ft
# w2v_model: wavlm-large
freeze_wav2vec: True
freeze_feature_extractor_wav2vec: True # procs when freeze_wav2vec = False, only retrain transformers
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/no_paraphasia/S2S/<w2v_model>-Transformer/AB_tokenizer-3000-bpe
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
data_dir: /z/mkperez/speechbrain/AphasiaBank/data/no_paraphasia
# data_dir: /z/mkperez/speechbrain/AphasiaBank/data/Duc_process/mtl_paraphasia
data_folder: !ref <data_dir>

# URL for the biggest Fairseq english wav2vec2 model.
wav2vec2_hub: !ref facebook/<w2v_model>
# wav2vec2_hub: !ref microsoft/<w2v_model>

# Data files
train_splits: ["train"]
dev_splits: ["dev"]
test_splits: ["test"]
skip_prep: False
ckpt_interval_minutes: 25 # save checkpoint every N min
train_csv: !ref <data_dir>/train.csv
valid_csv: !ref <data_dir>/dev.csv
test_csv: !ref <data_dir>/test.csv

# Training parameters
sorting: ascending
auto_mix_prec: False
sample_rate: 16000
max_length: 10 # change to 20
min_length: 0.5
max_sev_train: 4
min_sev_train: -1
batch_size: 24 # 32,3
test_batch_size: 1 # 32,3
grad_accumulation_factor: 4 #4,16
loss_reduction: 'batchmean'


# Dataloader options
train_dataloader_opts:
   batch_size: !ref <batch_size>

valid_dataloader_opts:
   batch_size: !ref <batch_size>

test_dataloader_opts:
   batch_size: !ref <test_batch_size>


# opt_class: !name:torch.optim.Adam
#    lr: !ref <lr>
#    eps: 1.e-8
opt_class: !name:torch.optim.Adadelta
   lr: !ref <lr>
   rho: 0.95
   eps: 1.e-8

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
dnn_neurons: 1024
emb_size: 128
dec_neurons: 1024
output_neurons: 3000  # Number of tokens (same as LM)


blank_index: 0
label_smoothing: 0.0
pad_index: 0
bos_index: 1
eos_index: 2
#SP
token_type: "bpe"


number_of_ctc_epochs: 7
ctc_weight: 0.5

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
valid_beam_size: 10
test_beam_size: 20
eos_threshold: 1.5
using_max_attn_shift: True
max_attn_shift: 240
lm_weight: 0.50
ctc_weight_decode: 0.0
coverage_penalty: 1.5
temperature: 1.25
temperature_lm: 1.25

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounterWithStopper
   limit: !ref <number_of_epochs>
   limit_to_stop: 7
   limit_warmup: 5
   direction: "min"

normalize: !new:speechbrain.processing.features.InputNormalization
   norm_type: global

# compute_features: !new:speechbrain.lobes.features.Fbank
#    sample_rate: !ref <sample_rate>
#    n_fft: !ref <n_fft>
#    n_mels: !ref <n_mels>


augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
   sample_rate: !ref <sample_rate>
   speeds: [95, 100, 105]

enc: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
   source: !ref <wav2vec2_hub>
   output_norm: True
   freeze: !ref True
   freeze_feature_extractor: !ref True
   save_path: !ref <save_folder>/wav2vec2_checkpoint

emb: !new:speechbrain.nnet.embedding.Embedding
   num_embeddings: !ref <output_neurons>
   embedding_dim: !ref <emb_size>


dec: !new:speechbrain.lobes.models.transformer.TransformerASR.TransformerASR # taken from transformer.yaml
    input_size: !ref <dec_neurons>
    tgt_vocab: !ref <output_neurons>
    d_model: !ref <dec_neurons>
    nhead: 4
    num_encoder_layers: 12
    num_decoder_layers: 6
    d_ffn: 2048
    dropout: 0.1
    activation: !name:torch.nn.GELU
    encoder_module: transformer
    attention_type: regularMHA
    normalize_before: True
    causal: False


ctc_lin: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <dnn_neurons>
   n_neurons: !ref <output_neurons>

seq_lin: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <dec_neurons>
   n_neurons: !ref <output_neurons>

log_softmax: !new:speechbrain.nnet.activations.Softmax
   apply_log: True

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
   blank_index: !ref <blank_index>
   reduction: !ref <loss_reduction>

seq_cost: !name:speechbrain.nnet.losses.kldiv_loss
    label_smoothing: !ref <label_smoothing>
    reduction: !ref <loss_reduction>

# This is the RNNLM that is used according to the Huggingface repository
# NB: It has to match the pre-trained RNNLM!!
lm_model: !new:speechbrain.lobes.models.RNNLM.RNNLM
   output_neurons: !ref <output_neurons>
   embedding_dim: !ref <emb_size>
   activation: !name:torch.nn.LeakyReLU
   dropout: 0.0
   rnn_layers: 2
   rnn_neurons: 2048
   dnn_blocks: 1
   dnn_neurons: 512
   return_hidden: True  # For inference

tokenizer: !new:sentencepiece.SentencePieceProcessor

# Models
modules:
   enc: !ref <enc>
   emb: !ref <emb>
   dec: !ref <dec>
   ctc_lin: !ref <ctc_lin>
   seq_lin: !ref <seq_lin>
   normalize: !ref <normalize>
   lm_model: !ref <lm_model>

model: !new:torch.nn.ModuleList
   - [!ref <enc>, !ref <emb>, !ref <dec>, !ref <ctc_lin>, !ref <seq_lin>]

valid_search: !new:speechbrain.decoders.S2STransformerBeamSearch
    modules: [!ref <dec>, !ref <seq_lin>, !ref <ctc_lin>]
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    blank_index: !ref <blank_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <valid_beam_size>
    ctc_weight: !ref <ctc_weight_decode>
    using_eos_threshold: False
    length_normalization: False

test_search: !new:speechbrain.decoders.S2STransformerBeamSearch
    modules: [!ref <dec>, !ref <seq_lin>, !ref <ctc_lin>]
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    blank_index: !ref <blank_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <test_beam_size>
    ctc_weight: !ref <ctc_weight_decode>
    lm_weight: !ref <lm_weight>
    lm_modules: !ref <lm_model>
    temperature: 1.15
    temperature_lm: 1.15
    using_eos_threshold: False
    length_normalization: True

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr>
   improvement_threshold: 0.0025
   annealing_factor: 0.8
   patient: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_folder>
   recoverables:
      model: !ref <model>
      scheduler: !ref <lr_annealing>
      normalizer: !ref <normalize>
      counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
   split_tokens: True

# The pretrainer allows a mapping between pretrained files and instances that
# are declared in the yaml. E.g here, we will download the file lm.ckpt
# and it will be loaded into "lm" which is pointing to the <lm_model> defined
# before.
pretrained_lm_tokenizer_path: speechbrain/asr-crdnn-rnnlm-librispeech
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
   collect_in: !ref <save_folder>
   loadables:
      lm: !ref <lm_model>
      tokenizer: !ref <tokenizer>
   paths:
      lm: !ref <pretrained_lm_tokenizer_path>/lm.ckpt
      tokenizer: !ref <pretrained_lm_tokenizer_path>/tokenizer.ckpt
